---
title: "assignment_7"
author: "Wouter"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(dslabs)
library(readr)
library(DBI)
```

# assignment_7

```{r}
# lees de data in
fluDf <- read_csv(here("assignment_7", "flu_data.csv"), skip = 11)
dengueDf <- read_csv(here("assignment_7", "dengue.csv"), skip = 11)
gapminderDf <- data.frame(gapminder)

# maak de griep en dengue data tidy want er zaten meerdere observaties op 1 rij
tidyFlu <- fluDf %>% pivot_longer(cols=tail(colnames(fluDf), n= 29), names_to= "country", values_to= "fluActivity")
tidyDengue <- dengueDf %>% pivot_longer(cols= tail(colnames(dengueDf), n= 10), names_to= "country", values_to= "dengueActivity")

# maak de datatype voor de country en year kolommen hetzelfde over de verschillende tabellen
gapminderDf$country <- as.character(gapminderDf$country)
tidyFlu <- tidyFlu %>% separate(col = Date, into = c("year", "month", "day"), sep = "-")
tidyDengue <- tidyDengue %>% separate(col = Date, into = c("year", "month", "day"), sep = "-")

# kijk of de datatypes nu overeenkomen en verken verder de data
summary(tidyDengue)
summary(tidyFlu)
summary(gapminderDf)
```

```{r, eval = FALSE}
# sla de gecleande data op
write.csv(tidyFlu, file = here("assignment_7", "tidyFlu.csv"), row.names = FALSE)
write.csv(tidyDengue, file = here("assignment_7", "tidyDengue.csv"))
write.csv(gapminderDf, file = here("assignment_7", "gapminderDf.csv"))
write_rds(tidyFlu, file = here("assignment_7", "tidyFlu.rds"))
write_rds(tidyDengue, file = here("assignment_7", "tidyDengue.rds"))
write_rds(gapminderDf, file = here("assignment_7", "gapminderDf.rds"))
```

```{r, eval = FALSE}
# maak een con object als connectie maar dan met het eigen wachtwoord
con <- dbConnect(RPostgres::Postgres(),
                 dbname = "workflowsdb",
                 host="localhost",
                 port="5432",
                 user="postgres",
                 password="password")

# laad de tabellen in de database in
dbWriteTable(con, "tidyFlu", read_csv(here("assignment_7", "tidyFlu.csv")), overwrite = TRUE)
dbWriteTable(con, "tidyDengue", read_csv(here("assignment_7", "tidyDengue.csv")), overwrite = TRUE)
dbWriteTable(con, "gapminderDf", read_csv(here("assignment_7", "gapminderDf.csv")), overwrite = TRUE)
```

```{r}
# maak een con object als connectie maar dan met het eigen wachtwoord
con <- dbConnect(RPostgres::Postgres(),
                 dbname = "workflowsdb",
                 host="localhost",
                 port="5432",
                 user="postgres",
                 password="password")

# laat de namen van de verschillende tabellen in de database zien
dbListTables(con)

# laat de namen van de kolommen van de verschillende tabellen zien
dbListFields(con, dbListTables(con)[1])
dbListFields(con, dbListTables(con)[2])
dbListFields(con, dbListTables(con)[3])

# geef een summary van alle tabellen in de database
summary(dbReadTable(con, dbListTables(con)[1]))
summary(dbReadTable(con, dbListTables(con)[2]))
summary(dbReadTable(con, dbListTables(con)[3]))

# join de gapminder tabel met de tidyflu tabel
joined <- dbGetQuery(con, "SELECT * 
           FROM \"gapminderDf\" 
           INNER JOIN \"tidyFlu\" 
           ON \"gapminderDf\".year = \"tidyFlu\".year 
           AND \"gapminderDf\".country = \"tidyFlu\".country")
joined
joined %>%   ggplot(aes(color = region, y = life_expectancy)) + 
  geom_boxplot() +
  labs(title = "Levensverwachting per regio",
       y = "Levensverwachting in jaren",
       color = "Regio's") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

joined %>% filter(country == "Argentina") %>% ggplot(aes(x = year, y = infant_mortality)) + 
  geom_line() + 
  scale_x_continuous(breaks = seq(2000,2020,1)) + 
  scale_y_continuous(breaks = seq(10,20,1)) + 
  labs(title = "Kindersterfte per jaar in Argentinië",
       x = "Jaren",
       y = "Kindersterfte per duizend kinderen")

joined %>% ggplot(aes(x = "", y = gdp, fill = continent)) +
  geom_col() + 
  coord_polar(theta = "y") + 
  theme_void() + 
  labs(title = "Verhouding BBP per continent",
       fill = "Continent")
```

14. Write a short report to show at least the actions listed in this assignment in a Rmd file for your portfolio. Include pictures and provide text explaining and showcasing your skills.
