---
title: "CV Wouter Verra"
author: "WouterVerra"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CV Wouter Verra

<p style="font-size: x-large">Algemene informatie</p>
Naam:			Wouter Verra <br>
Adres: 			- <br>
Telefoonnummer: 	- <br>
E-mailadres: 		- <br>
Geboortedatum: 	10 April 1996 <br>
Geslacht: 		Man <br>
Nationaliteit: 		Nederlandse <br>
Burgerlijke staat: 	Ongehuwd <br>

<p style="font-size: x-large">Opleidingen:</p>
Biologisch en Medisch Laboratorium Onderzoek te Utrecht, september 2018 tot heden <br>
Keltische Talen en Cultuur te Utrecht, september 2016 tot mei 2016 <br>
University Foundation Year (afgerond) Education First te Oxford, September 2015 tot mei 2016 <br>
VWO (afgerond) Marecollege te Leiden, September 2007 tot juni 2015 <br>

<p style="font-size: x-large">Werkervaring:</p>
Hadro techniek, assemblage medewerker, september 2017 tot augustus 2018 <br>
Van Vliet The Candy Company, orderpicker, juni 2017 tot september 2017 <br>
Mc Donalds Bodegraven, crewlid, mei 2016 tot juni 2017

<p style="font-size: x-large">Vaardigheden:</p>

<p style="font-size: large">Programeertalen:</p>
R <br>
Bash <br>

<p style="font-size: large">Programma's:</p>
Rstudio <br>
Excel <br>
SPSS

<p style="font-size: large">Talen:</p>
Nederlands (moedertaal) <br>
Engels (vloeiend)

<p style="font-size: x-large">Hobby’s:</p>
Roeien <br>
Boulderen
