---
title: "assignment_9"
author: "WouterVerra"
date: "`r Sys.Date()`"
output: html_document
params:
  country: "Austria"
  year: 2022
  month: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

# parameterization of Rmarkdown documents

```{r, eval=FALSE}
# onuitgevoerd blok om makkelijk zelf de parameters van dit bestand aan te passen
rmarkdown::render(here("assignment_9", "assignment_9.Rmd"), params = list(country = "Greece", year = 2021, month = 6))
```


```{r}
# read  in csv with covid data
covid_data <- read.csv(here("assignment_9", "data.csv"))

# filter op land
covid_data <- covid_data %>% filter(countriesAndTerritories == params$country)

# filter op jaar
covid_data <- covid_data %>% filter(year == params$year)

# filter op maand
covid_data <- covid_data %>% filter(month == params$month)

# plot the cases
covid_data %>% 
  ggplot(aes(x= day, y= cases)) +
  geom_line() +
  geom_point() +
  labs(title= paste0("Covid 19 cases in: ", params$country, " in: ", params$month, "/", params$year), y= "Covid cases")

# plot the deaths
covid_data %>% 
  ggplot(aes(x= day, y= deaths)) +
  geom_line() +
  geom_point() +
  labs(title= paste0("Covid 19 deaths in: ", params$country, " in: ", params$month, "/", params$year), y= "Covid deaths")
```

